import { testThrow } from './src/throw';
import ApiErrorHandler from './rollbar-err';

describe('TestErr', () => {
    describe('#testThrow', () => {
        it('should throw an error generated by testThrow', async () => {
            ApiErrorHandler.generateError = jest.fn().mockReturnValue(new Error('Mocked Error'));
            await expect(testThrow()).rejects.toThrow(/Mocked Error/);
        });
    });
});

export {};